# Generated by Django 4.2.21 on 2025-05-09 12:49

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterType',
            fields=[
                ('param_id', models.AutoField(help_text='ID метеопараметра', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Название метеопараметра', max_length=50)),
                ('unit', models.CharField(help_text='Ед. измерения', max_length=20)),
            ],
            options={
                'verbose_name': 'Типы метеопараметров',
                'db_table': 'Parameters',
            },
        ),
        migrations.CreateModel(
            name='SensorSeries',
            fields=[
                ('series_id', models.AutoField(help_text='ID модели датчика', primary_key=True, serialize=False)),
                ('series_name', models.CharField(help_text='Название модели датчика', max_length=255)),
                ('manufacturer', models.CharField(help_text='Название производителя', max_length=255)),
                ('precision', models.DecimalField(decimal_places=8, help_text='Погрешность измерения', max_digits=10)),
                ('min_max', django.contrib.postgres.fields.ranges.IntegerRangeField()),
            ],
            options={
                'verbose_name': 'Модель датчика',
                'db_table': 'Sensor_Series',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.AutoField(help_text='ID станции', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Название станции', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Описание')),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Координаты: Широта', max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Координаты: Долгота', max_digits=10)),
                ('elevation', models.FloatField(help_text='Высота над уровнем моря')),
                ('soil_type', models.CharField(choices=[('PT', 'Торфяные'), ('PD', 'Подзолистые'), ('GF', 'Серые лесные'), ('CL', 'Глинистые/суглинки'), ('SL', 'Песчаные/супеси'), ('UR', 'Урбанизированные'), ('MT', 'Горные'), ('FP', 'Пойменные')], default='PD', max_length=10)),
            ],
            options={
                'verbose_name': 'Метеостанция',
                'db_table': 'Stations',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sensor_id', models.AutoField(help_text='ID датчика', primary_key=True, serialize=False)),
                ('last_spoke', models.DateTimeField(help_text='Дата и время последнего показания')),
                ('sensor_model_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stations.sensorseries')),
                ('station_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stations.station')),
            ],
            options={
                'verbose_name': 'Датчик',
                'db_table': 'Sensors',
            },
        ),
    ]
