# Generated by Django 4.2.21 on 2025-05-09 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametertype',
            options={'verbose_name': 'Тип метеопараметра', 'verbose_name_plural': 'Типы метеопараметров'},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'verbose_name': 'Датчик', 'verbose_name_plural': 'Датчики'},
        ),
        migrations.AlterModelOptions(
            name='sensorseries',
            options={'verbose_name': 'Модель датчика', 'verbose_name_plural': 'Модели датчиков'},
        ),
        migrations.AlterModelOptions(
            name='station',
            options={'verbose_name': 'Метеостанция', 'verbose_name_plural': 'Метеостанции'},
        ),
    ]
