# Generated by Django 4.2.21 on 2025-05-09 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_alter_parametertype_options_alter_sensor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorseries',
            name='param_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='stations.parametertype'),
            preserve_default=False,
        ),
    ]
