# Generated by Django 4.2.21 on 2025-05-09 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_alter_sensor_sensor_model_id_alter_sensor_station_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='sensor_model_id',
            new_name='sensor_model',
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='station_id',
            new_name='station',
        ),
    ]
