# Generated by Django 4.2.21 on 2025-05-11 21:05

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0005_rename_sensor_model_id_sensor_sensor_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorseries',
            name='value_range',
            field=django.contrib.postgres.fields.ranges.DecimalRangeField(default=(0, 10)),
            preserve_default=False,
        ),
    ]
