# Generated by Django 4.2.21 on 2025-05-11 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0006_sensorseries_value_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorseries',
            name='min_max',
        ),
    ]
