# Generated by Django 4.2.21 on 2025-06-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0007_remove_sensorseries_min_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametertype',
            name='code',
            field=models.CharField(default='unknown', help_text='Аббревиация', max_length=20),
            preserve_default=False,
        ),
    ]
