# Generated by Django 4.2.21 on 2025-06-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0009_alter_parametertype_code'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['station_id'], name='sensors_station_id_idx'),
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['sensor_model_id'], name='sensors_model_id_idx'),
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['station_id', 'sensor_model_id'], name='sensors_station_model_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorseries',
            index=models.Index(fields=['param_type_id'], name='sensor_series_param_type_idx'),
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['latitude', 'longitude'], name='stations_lat_lon_idx'),
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['name'], name='stations_name_idx'),
        ),
    ]
