# Generated by Django 4.2.21 on 2025-05-09 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(help_text='Дата и время наблюдения')),
                ('value', models.FloatField(help_text='Значение')),
                ('sensor', models.ForeignKey(help_text='ID Датчика', on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='stations.sensor')),
            ],
            options={
                'verbose_name': 'Наблюдение',
                'db_table': 'Readings',
            },
        ),
    ]
