# Generated by Django 4.2.21 on 2025-05-09 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reading',
            options={'verbose_name': 'Наблюдение', 'verbose_name_plural': 'Наблюдения'},
        ),
    ]
