# Generated by Django 4.2.21 on 2025-05-11 20:48
from django.db import migrations
from django.db import migrations
import datetime
import random
import numpy as np
from numpy.random import lognormal

def paste_dummy_winds(apps, schema_editor): # We can't import the model directly as it may be a newer version => use historical
    Reading = apps.get_model("readings", "Reading")  # получаем модель датчика
    Sensor = apps.get_model("stations", "Sensor")  # получаем модель датчика   
    wind_sens = Sensor.objects.filter(sensor_model__param_type__name="Скорость ветра") # получили все датчики скорости ветра
    
    sigma = 0.5  # Adjust as needed for desired mode
    mode = 10
    mu = np.log(mode) + sigma**2

    # Generate wind speed samples
    wind_speeds = np.random.lognormal(mean=mu, sigma=sigma, size=40)
    wind_speeds = np.clip(wind_speeds, 0.6, 60)

    start = datetime.datetime(2024, 3, 1, 12, 0) # задаем дату начала
    timestamps = [ start + datetime.timedelta(days=x) for x in range(0, 30)]
    readings_to_make = []

    for i in range(0, 30):
        for cur_sensor in wind_sens:
            readings_to_make.append(
                Reading(
                    timestamp = timestamps[i],
                    sensor = cur_sensor,
                    value = wind_speeds[i]
                ))
    Reading.objects.bulk_create(readings_to_make)

    print("Данные успешно созданы")

class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0003_auto_20250509_2146'),
        ('stations', '0007_remove_sensorseries_min_max')
    ]

    operations = [
        migrations.RunPython(paste_dummy_winds),
    ]
