# Generated by Django 4.2.21 on 2025-06-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0005_auto_20250512_0230'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reading',
            index=models.Index(fields=['timestamp'], name='readings_timestamp_idx'),
        ),
        migrations.AddIndex(
            model_name='reading',
            index=models.Index(fields=['sensor_id'], name='readings_sensor_id_idx'),
        ),
        migrations.AddIndex(
            model_name='reading',
            index=models.Index(fields=['sensor_id', 'timestamp'], name='readings_sensor_timestamp_idx'),
        ),
    ]
